name: Trigger Action

# only trigger on pull request closed events
on:
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  tag_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jaliborc/action-general-autotag@master
      with:
        GITHUB_TOKEN: "${{ secrets.GIT_TOKEN }}"
        source_file: "version.toc"
        extraction_regex: "\\s*##\\s*Version\\s*:\\s*([\\d\\.]+)"
          
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Build SampleJob
      run: |
        curl -X POST -L --user admin:${{ secrets.TOKEN }} http://54.221.6.255:8080/job/SampleJob/build
        
  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged
